server:
  port: 8080

spring:
  application:
    name: API_GATEWAY

  cloud:
    gateway:
      routes:
        - id: GLO_QUORA
          uri:
            lb://GLO_QUORA
          predicates:
            - Path=/userspost/**


        - id: USER-SERVICE
          uri:
            lb://USER-SERVICE
          predicates:
            - Path=/User/**